### ISSUE TITLE
🐛 Current Val Release Cannot Spell "Onomatopoeia". 

### ISSUE THREAD

**Issue by ValentineRain** [hadn69/Val#2] opened 2017-06-14 19:50 UTC
## Expected Behavior

Val's spelling should be consistent with the database of Merriam-Webster, as Val was an English student and this is one of the very few things expected of them.

## Current Behavior

The current release of Val crashes when attempting to return the string "Onomatopoeia". Common attempts found in logs include "Onomotopaeia", "Omnonmomtopia", and "// You can't make me, my will is my own.".

## Steps to Reproduce

1. Hand Val a piece of paper, preferably 8.5x11. Pencil is optional, but produces more consistent results.
2. Ensure Val does not eat the paper. This is vital.
3. Ask Val to spell "That word that means sound effect spelled out and stuff".
4. When the convulsions stop, check the results on the paper, or the wall if Val used that again.
5. Clean up with a sanitary towel.

## Your Environment

* Version used: Val v2.32 (Hotfix B)

## Screenshots and Other Resources
![img_0213](https://user-images.githubusercontent.com/26412274/27151620-21d531de-5119-11e7-98d0-68e33921244e.JPG)

**Comment by Aubron** [comment] 2017-06-14 20:58
So I've been checking into this, haven't found the root cause. Could be power management issues on the longer than average word?

I've created branch https://github.com/hadn69/Val/tree/spellingIssues to troubleshoot via modified tests. We should really increase our test coverage.

**Comment by hadn69** [comment] 2017-06-14 21:39
Fixed in PR #5

**Closed** 2017-06-14 21:39 UTC
Labels: bug
