### ISSUE TITLE
🐛 Unit Has Sudden, Uncontrollable Fear of Aubron

### ISSUE THREAD

**Issue by ValentineRain** [hadn69/Val#13] opened 2017-07-13 15:47 UTC
Since closure of issue #10 , which was resolved by implementing @Aubron as Val's parent class, the unit is now irrationally afraid of @Aubron and will not stop screaming.

This may be a deeper issue than originally thought, possibly at the operating system level.

**Comment by Aubron** [comment] 2017-07-13 15:47
Working as intended, wontfix.

**Comment by ValentineRain** [comment] 2017-07-13 15:47
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by hadn69** [comment] 2017-09-20 22:38
oops

**Closed by hadn69** 2017-09-20 22:38 UTC
Labels: wontfix

**Comment by hadn69** [comment] 2017-09-20 22:40
This might be an issue with [https://github.com/hadn69/Aubron/](Aubron) project.
